version: "3.8" 

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.12
    container_name: pyspark-workspace
    volumes:
      - ..:/workspaces/pyspark-hands-on
    command: sleep infinity
    depends_on:
      - mysql

  mysql:
    image: mysql:9.5.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sparkdb
      MYSQL_USER: spark
      MYSQL_PASSWORD: spark
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
